Repository bongtubaekseo/BongBaek-Android, pull requests merged in 2025-07, with the labels that each got.

#10 [DOCS/#9] 리드미 작성
  README.md
Labels: DOCS 📝, 승준 🙋

#14 [UI/#3] 공통 컴포넌트 구현
  app/src/main/java/com/bongtu/baekseo/BongBaekApplication.kt
  app/src/main/java/com/bongtu/baekseo/core/common/type/.gitkeep
  app/src/main/java/com/bongtu/baekseo/core/common/type/ButtonType.kt
  app/src/main/java/com/bongtu/baekseo/core/common/type/EventType.kt
  app/src/main/java/com/bongtu/baekseo/core/common/type/TopBarType.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/.gitkeep
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/badge/BongBaekBadge.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/button/BongBaekButton.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/chip/BongBaekChip.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/topbar/BongBaekTopBar.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/theme/Color.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/theme/Theme.kt
  app/src/main/java/com/bongtu/baekseo/core/util/ModifierExt.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainActivity.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainNavigator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainTab.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/component/MainBottomBar.kt
  app/src/main/res/drawable/ic_dollar.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_pen.xml
Labels: UI 📱, 종명 🙋‍♂️

#16 [UI/#11] 공통 컴포넌트 구현
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/BongBaekInnerTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/LabelTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/RoundedBoxTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/SearchTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/TextFieldValidateResult.kt
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/values/strings.xml
Labels: UI 📱, 승준 🙋

#27 [HOTFIX/#26]공통 TextField 패딩, RoundedTextField 수정
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/LabelTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/RoundedBoxTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/SearchTextField.kt
Labels: HOTFIX 🛠️, UI 📱, 승준 🙋

#25 [UI/#20] 기록하기 뷰 구현
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/chip/BongBaekChip.kt
  app/src/main/java/com/bongtu/baekseo/core/util/LocalDateExt.kt
  app/src/main/java/com/bongtu/baekseo/data/model/RecordEvent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainNavigator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainTab.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/AttendTypeTab.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/EventCategoryBar.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/model/RecordEventMapper.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/model/YearMonthEventItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/navigation/RecordNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/type/AttendType.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/type/EventCategoryType.kt
  app/src/main/res/values/strings.xml
Labels: UI 📱, 승준 🙋

#29 [UI/#23] 금액추천 UI 구현 파트2
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendIntroScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendDateCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventSelector.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendParticipationCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendRelationSelector.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendTextFieldCard.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/values/strings.xml
Labels: UI 📱, 종명 🙋‍♂️

#41 [UI/#35] 금액추천 UI 구현.. 그 마지막...
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/LottieOverlay.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/button/BongBaekButton.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/progressbar/BongBaekProgressBar.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/theme/Color.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendRecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendResultScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventLocationContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendExpenseCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendLoadingOverlay.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendResultContent.kt
  app/src/main/res/drawable/ic_info_primary.xml
  app/src/main/res/values/strings.xml
Labels: UI 📱, 종명 🙋‍♂️

#40 [UI/#32] 기록 상세보기 UI 구현
  app/src/main/java/com/bongtu/baekseo/core/designsystem/theme/Color.kt
  app/src/main/java/com/bongtu/baekseo/core/util/LocalDateExt.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordDetailScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordDetailDropDown.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/type/RecordDetailDropDownTrailingType.kt
  app/src/main/res/drawable/ic_check_gray.xml
  app/src/main/res/values/strings.xml
Labels: UI 📱, 승준 🙋

#44 [UI/#39] 전체 일정 UI
  app/src/main/java/com/bongtu/baekseo/core/util/LocalDateExt.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/navigation/HomeRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/model/ScheduleEvent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/model/ScheduleEventMapper.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/model/ScheduleYearMonthEventItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/navigation/ScheduleNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/res/values/strings.xml
Labels: UI 📱, 혜정 🙋‍♀️

#47 [UI/#45] 홈 UI 구현(Part 3)
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/component/HomePageCard.kt
Labels: UI 📱, 혜정 🙋‍♀️

#49 [UI/#46] 스플래시 UI 구현
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainNavigator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/navigation/SplashNavigation.kt
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/drawable/ic_splash_name.xml
Labels: UI 📱, 혜정 🙋‍♀️

#52 [FEAT/#42] 금액추천 뷰 로직 구현
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/TextFieldValidateResult.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainNavigator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendFinalScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendResultScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendTextFieldCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/navigation/RecommendNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/navigation/RecommendRoute.kt
Labels: FEAT ✨, 종명 🙋‍♂️

#54 [ADD/#53] API 연결 기본 세팅
  app/src/main/java/com/bongtu/baekseo/core/network/HeaderInterceptor.kt
  app/src/main/java/com/bongtu/baekseo/core/network/NetworkModule.kt
  app/src/main/java/com/bongtu/baekseo/core/network/di/NetworkModule.kt
  app/src/main/java/com/bongtu/baekseo/core/network/model/BaseResponse.kt
  app/src/main/java/com/bongtu/baekseo/core/network/qualifier/NetworkQualifier.kt
Labels: ADD ➕, 종명 🙋‍♂️

#57 [FEAT/#55] 금액 추천 API 구현
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/di/event/EventDataSourceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/event/EventRepositoryModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/event/EventServiceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/EventInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/HighAccuracyDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/HostInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/LocationInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/PostEventCostRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/PostEventCostResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/PostEventInfoRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/EventMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/Cost.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/Event.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/HighAccuracy.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/Host.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/Location.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/event/EventRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
Labels: FEAT ✨, 종명 🙋‍♂️

#59 [ADD/#51] 카카오 로그인 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bongtu/baekseo/BongBaekApplication.kt
  app/src/main/java/com/bongtu/baekseo/core/local/datastore/TokenDataStore.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingLoginKakaoLauncher.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingLoginScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT ✨, 혜정 🙋‍♀️

#60 [FEAT/#56] 홈 뷰 로직 구현
  app/src/main/java/com/bongtu/baekseo/core/common/type/IncomeType.kt
  app/src/main/java/com/bongtu/baekseo/core/local/datastore/DataStoreModule.kt
  app/src/main/java/com/bongtu/baekseo/core/local/datastore/UsernameDataStore.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/oauth/KakaoLoginInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingSettingScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
Labels: FEAT ✨, 혜정 🙋‍♀️

#64 [FEAT/#58] 카카오 지도 세팅 및 연동
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bongtu/baekseo/BongBaekApplication.kt
  app/src/main/java/com/bongtu/baekseo/core/network/KakaoHeaderInterceptor.kt
  app/src/main/java/com/bongtu/baekseo/core/network/di/NetworkModule.kt
  app/src/main/java/com/bongtu/baekseo/core/network/qualifier/NetworkQualifier.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/map/KakaoMapDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/map/KakaoMapDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/di/map/KakaoMapDataSourceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/map/KakaoMapRepositoryModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/map/KakaoMapServiceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/map/KakaoMapResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/KakaoMapMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/map/Place.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/map/KakaoMapRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/map/KakaoMapRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/map/KakaoMapService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventLocationContent.kt
  app/src/main/res/drawable/img_map_marker.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEAT ✨, 종명 🙋‍♂️

#61 [UI/#50] 기록 수정하기 View 구현(Part 2)
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/component/DetailDropDown.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/type/DetailDropDownTrailingType.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditLocationScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/navigation/RecommendNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordDefaultScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordTopBar.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/navigation/RecordNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/navigation/RecordRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/type/RecordDetailDropDownTrailingType.kt
  app/src/main/res/values/strings.xml
Labels: UI 📱, 승준 🙋

#66 [Feat/#63] 온보딩 뷰 로직 구현
  app/src/main/java/com/bongtu/baekseo/core/util/StringExt.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/auth/AuthDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/auth/AuthDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/di/auth/AuthDataSourceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/auth/AuthRepositoryModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/auth/AuthServiceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/KakaoLoginInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostKakaoLoginRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostKakaoLoginResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostSignUpRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostTokenReissueRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostTokenReissueResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/AuthMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/auth/KakaoLogin.kt
  app/src/main/java/com/bongtu/baekseo/data/model/auth/TokenReissue.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/auth/AuthService.kt
  app/src/main/java/com/bongtu/baekseo/domain/usecase/.gitkeep
  app/src/main/java/com/bongtu/baekseo/domain/usecase/auth/CheckAutoLoginUseCase.kt
  app/src/main/java/com/bongtu/baekseo/domain/usecase/auth/SetKakaoLoginUseCase.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingLoginKakaoLauncher.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingLoginScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingSettingScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashViewModel.kt
Labels: FEAT ✨, 혜정 🙋‍♀️

#69 [FEAT/#67] 홈 뷰 API 연동
  app/src/main/java/com/bongtu/baekseo/core/util/StringExt.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/FetchHomeEventsResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/EventMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/HomeEvent.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/event/EventRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/component/HomePageCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/component/HomeScheduleCard.kt
Labels: FEAT ✨, 혜정 🙋‍♀️

#68 [FEAT/#62] 기록하기 뷰 로직 구현
  app/src/main/java/com/bongtu/baekseo/core/common/type/AttendType.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/AttendTypeTab.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/navigation/RecordNavigation.kt
Labels: FEAT ✨, 승준 🙋

#77 [REFACTOR/#76] 수정하기 뷰 네비 분기처리
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/type/EditEntryType.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
Labels: REFACTOR ♻️, 승준 🙋

#80 [FEAT/#70] 전체 일정 뷰 API 연동
  app/src/main/java/com/bongtu/baekseo/core/util/LazyListStateExt.kt
  app/src/main/java/com/bongtu/baekseo/core/util/StringExt.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/di/auth/AuthServiceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/GetHomeEventsResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/GetScheduleEventsResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/EventMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/ScheduleEvent.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/event/EventRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleEmptyContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/model/ScheduleEventMapper.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/model/ScheduleYearMonthEventItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, 혜정 🙋‍♀️

#81 [FEAT/#75] 수정하기 로직 및 API 구현
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/TextFieldValidateResult.kt
  app/src/main/java/com/bongtu/baekseo/core/util/CostTextFieldFormat.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/PutEventInfoRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/event/EventRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditLocationScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditCostTextField.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditLocationContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditMemoContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditSaveButton.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditNavigation.kt
  app/src/main/res/values/strings.xml
Labels: FEAT ✨, 승준 🙋

#87 [REFACTOR/#85] 금액추천 자잘한 리팩토링
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/RoundedBoxTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/SearchTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/util/TextFieldValidator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendLoadingScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendDateCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventLocationContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendRelationTypeContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendTextFieldCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/navigation/RecommendNavigation.kt
Labels: REFACTOR ♻️, 종명 🙋‍♂️

#90 [FEAT/#88] 기록하기 API 연동
  app/src/main/java/com/bongtu/baekseo/core/common/type/AttendType.kt
  app/src/main/java/com/bongtu/baekseo/core/network/di/NetworkModule.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/DeleteEventsDto.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/event/DeleteEventsRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/EventMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/DeleteEvent.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/event/EventRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleEmptyContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/model/RecordEventMapper.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/model/YearMonthEventItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashViewModel.kt
Labels: FEAT ✨, 혜정 🙋‍♀️

#104 [FIX/#103] QA 수정사항 반영
  app/build.gradle.kts
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingSettingScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
  gradle/libs.versions.toml
Labels: FIX 🔨, 혜정 🙋‍♀️

#108 [REFACTOR/#107] 자잘한 이슈 해결 2
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainActivity.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/component/OnBoardingBottomSheet.kt
Labels: REFACTOR ♻️, 종명 🙋‍♂️

#111 [REFACTOR/#109] UX를 저해하는 사소한 문제들 해결
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/dropdownmenu/BongBaekDropDown.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/BongBaekInnerTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/SearchTextField.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditLocationScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditMemoContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/schedule/component/ScheduleListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventLocationContent.kt
Labels: REFACTOR ♻️, 종명 🙋‍♂️

#112 [DOCS] README 업데이트
  README.md
Labels: DOCS 📝, 승준 🙋
