Repository bongtubaekseo/BongBaek-Android, pull requests merged in 2025-09, with the labels that each got.

#141 [UI/#140] 탈퇴하기 UI 구현
  app/src/main/java/com/bongtu/baekseo/core/common/type/WithdrawType.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/BongBaekInnerTextField.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawQuitScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawReasonScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/component/WithdrawDialog.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/component/WithdrawReasonSelector.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/navigation/WithdrawNavigation.kt
  app/src/main/res/drawable/ic_withdraw_check.xml
  app/src/main/res/drawable/ic_withdraw_check_gray.xml
  app/src/main/res/drawable/img_withdraw_gift.png
  app/src/main/res/values/strings.xml
Labels: UI 📱, 혜정 🙋‍♀️

#149 [ADD/#133] Fastlane 설정
  .gitignore
  Gemfile
  Gemfile.lock
  app/build.gradle.kts
  app/proguard-rules.pro
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/README.md
  fastlane/metadata/android/ko-KR/changelogs/default.txt
  gradle/libs.versions.toml
Labels: ADD ➕, 종명 🙋‍♂️

#155 [FEAT/#150] 로그아웃 및 회원 탈퇴 API 연동
  app/src/main/java/com/bongtu/baekseo/core/common/type/WithdrawType.kt
  app/src/main/java/com/bongtu/baekseo/core/network/model/BaseResponseWithoutData.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/auth/AuthDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/member/MemberDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/auth/AuthDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/member/MemberDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/di/member/MemberDataSourceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/member/MemberRepositoryModule.kt
  app/src/main/java/com/bongtu/baekseo/data/di/member/MemberServiceModule.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/member/PostWithdrawRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/member/MemberRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/member/MemberRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/member/MemberService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/navigation/MyPageNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawQuitScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawReasonScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/component/WithdrawReasonSelector.kt
Labels: FEAT ✨, 혜정 🙋‍♀️

#156 [FEAT/#153] 마이페이지 뷰 API 연동
  app/src/main/java/com/bongtu/baekseo/core/common/type/IncomeType.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/member/MemberDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/member/MemberDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/member/ProfileInfoDto.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/MemberMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/member/ProfileInfo.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/member/MemberRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/member/MemberRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/member/MemberService.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/ProfileEditScreen.kt
Labels: FEAT ✨, 승준 🙋

#158 [REFACTOR/#157] 서버 api 응답 수정 사항 반영
  app/src/main/java/com/bongtu/baekseo/core/local/datastore/ApiKeyDataStore.kt
  app/src/main/java/com/bongtu/baekseo/core/local/datastore/DataStoreModule.kt
  app/src/main/java/com/bongtu/baekseo/core/network/KakaoHeaderInterceptor.kt
  app/src/main/java/com/bongtu/baekseo/core/network/di/NetworkModule.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/auth/AuthDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/datasourceimpl/event/EventDataSourceImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostKakaoLoginResponse.kt
  app/src/main/java/com/bongtu/baekseo/data/dto/auth/PostSignUpRequest.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/AuthMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/model/auth/KakaoLogin.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/auth/AuthRepository.kt
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/data/service/event/EventService.kt
  app/src/main/java/com/bongtu/baekseo/domain/usecase/auth/SetKakaoLoginUseCase.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingViewModel.kt
Labels: REFACTOR ♻️, 혜정 🙋‍♀️

#166 [HOTFIX/#164] CI Workflow 수정
  .github/workflows/android_develop.yml
Labels: HOTFIX 🛠️, 종명 🙋‍♂️

#160 [REFACTOR/#159] Dialog 공통 컴포넌트화
  app/src/main/java/com/bongtu/baekseo/core/common/type/DialogType.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/dialog/BongBaekDatePickerDialog.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/dialog/BongBaekDialog.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawReasonScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/component/WithdrawDialog.kt
  app/src/main/res/values/strings.xml
Labels: REFACTOR ♻️, 혜정 🙋‍♀️

#176 [FIX/#170] QA 반영
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/dropdownmenu/BongBaekDropDown.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/dropdownmenu/EmptyDropDown.kt
  app/src/main/java/com/bongtu/baekseo/core/util/ModifierExt.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditLocationScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditDropdownMenu.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditFieldItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendResultScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendEventLocationContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/component/RecommendSliderCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleViewModel.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, 종명 🙋‍♂️

#178 [HOTFIX/#177] CI Workflow 수정
  .github/workflows/android_develop.yml
Labels: HOTFIX 🛠️, 종명 🙋‍♂️

#179 [FIX/#175] 담당 화면 QA 반영(Part 2)
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/LabelTextField.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/component/DetailDropDown.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditDropdownMenu.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditFieldItem.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/component/EditMemoContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/mypage/ProfileEditScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/withdraw/component/WithdrawReasonSelector.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, 승준 🙋

#183 [HOTFIX/#182] 상세보기 뷰 삭제 상태값 수정
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailScreen.kt
Labels: HOTFIX 🛠️, 승준 🙋
