Repository bongtubaekseo/BongBaek-Android, pull requests merged in 2025-08, with the labels that each got.

#127 [REFACTOR/#126] 기록하기 뷰 리팩토링
  app/src/main/java/com/bongtu/baekseo/core/common/type/HomeScheduleCardInfoType.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/card/BongBaekScheduleCard.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/navigation/ScheduleNavigation.kt
Labels: REFACTOR ♻️, 혜정 🙋‍♀️

#131 [REFACTOR/#125] 로그인 Process Phoenix 수정
  app/src/main/java/com/bongtu/baekseo/data/repositoryimpl/auth/AuthRepositoryImpl.kt
  app/src/main/java/com/bongtu/baekseo/domain/usecase/auth/CheckAutoLoginUseCase.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainActivity.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainNavigator.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingSettingScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/SplashViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/splash/navigation/SplashNavigation.kt
Labels: REFACTOR ♻️, 혜정 🙋‍♀️

#129 [REFACTOR/#128] 화면 전환 간 데이터 전달 방식 변경
  app/src/main/java/com/bongtu/baekseo/core/local/cache/EventCache.kt
  app/src/main/java/com/bongtu/baekseo/data/model/RecordEvent.kt
  app/src/main/java/com/bongtu/baekseo/data/model/event/EditEvent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditLocationScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditMainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/EditViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditNavType.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/edit/navigation/EditRoute.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendResultScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/RecommendViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/recommend/navigation/RecommendNavigation.kt
Labels: REFACTOR ♻️, 승준 🙋

#124 [FIX/#114] BottomNavBar 코드 수정
  app/src/androidTest/java/com/bongtu/baekseo/ExampleInstrumentedTest.kt
  app/src/main/java/com/bongtu/baekseo/core/compositionlocal/LocalNavigationBarsPadding.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/BongBaekScheduleEmptyContent.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/list/BongBaekScheduleList.kt
  app/src/main/java/com/bongtu/baekseo/core/designsystem/component/textfield/BongBaekInnerTextField.kt
  app/src/main/java/com/bongtu/baekseo/core/util/DateValidator.kt
  app/src/main/java/com/bongtu/baekseo/core/util/LazyListStateExt.kt
  app/src/main/java/com/bongtu/baekseo/core/util/PaddingValuesExt.kt
  app/src/main/java/com/bongtu/baekseo/core/util/WindowInsetsExt.kt
  app/src/main/java/com/bongtu/baekseo/data/datasource/event/EventDataSource.kt
  app/src/main/java/com/bongtu/baekseo/data/mapper/EventMapper.kt
  app/src/main/java/com/bongtu/baekseo/data/repository/event/EventRepository.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/HomeScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/home/navigation/HomeNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/MainScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/main/component/MainBottomBar.kt
  app/src/main/java/com/bongtu/baekseo/presentation/onboarding/OnBoardingLoginScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/EventCategoryBar.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordListContent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/component/RecordTopBar.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/navigation/RecordNavigation.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleViewModel.kt
  app/src/main/res/values/strings.xml
Labels: FIX 🔨, 종명 🙋‍♂️

#136 [FIX/#135] 스케줄 카테고리 변경 시 발생하는 스크롤 점프 수정
  app/src/main/java/com/bongtu/baekseo/presentation/home/model/HomeEvent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordContract.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/record/RecordViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleScreen.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/ScheduleViewModel.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/model/ScheduleEvent.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/model/ScheduleEventMapper.kt
  app/src/main/java/com/bongtu/baekseo/presentation/schedule/model/ScheduleYearMonthEventItem.kt
Labels: FIX 🔨, 승준 🙋

#144 [ADD/#143] R8/Proguard 설정 + 키스토어 설정
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  keystore/debug.keystore
Labels: ADD ➕, 종명 🙋‍♂️
